### ISSUE TITLE
_train_variance_forward_seq

### ISSUE THREAD

**Issue by xchhuang** [NGoetz/NF#1]
Hi @NGoetz,

First thanks for releasing your implementation. I tried to run the example in readme, but got the following error:
```
line 244, in _train_variance_forward_seq
    integ[i+1]+=torch.mean(fres)/n_minibatches
IndexError: index 11 is out of bounds for dimension 0 with size 11
```
Do you have any idea why? Does the ``` integ``` array stores the integral value after each training epoch? Thanks in advance.

**Comment by NGoetz** [comment]
Hi!

Thank you for your interest in my project. I forgot to update the readme after some changes. Basically, I added another option to define the starting epoch in case one wants to interrupt training. You have to add a zero after the 300 in order to not run into this issue.
Yes, integ stores the integral value calculated in each epoch in case one wants to use them, although this is discouraged for integrands with high variance due to the behaviour of the traing.
In the updated readme, I have also linked a Demo Jupyter notebook which explains the usage a tiny bit better, but feel free to ask me!
Additionally, you should know that this project here is not continued anymore. Instead, I work on a further developed project, based on the same algorithm and with more extensive functionalities: https://github.com/ndeutschmann/zunis

**Comment by xchhuang** [comment]
Hi @NGoetz ,

Thank you for your reply. I found the Jupyter notebook Demo quite helpful! 

And I will take a look into the new projects. Thanks.
